# Generated by Django 5.0 on 2025-06-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_pgtrgm_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxonomy',
            name='grouping',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
