# Generated by Django 5.0 on 2025-06-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_taxonomy_grouping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='state',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
